version: "3"
services:
  db:
    container_name: dev_db
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: dev_db
    ports:
      - 3306:3306

    volumes:
      - ./data_dir:/var/lib/mysql
