"""20220127

Revision ID: b642c382a678
Revises: a7a42dc31405
Create Date: 2022-01-27 22:11:11.181863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b642c382a678'
down_revision = 'a7a42dc31405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=20), nullable=True))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
